easy_admin:
    site_name: '<img src="https://www.vidoomy.com/media/logo-vidoomy.png"/>'

    entities:
        Setup:
            class: App\Entity\Setup
            help: 'Update global parameters or create a custom rule for a publisher'
            label: 'Setup'
            list:
                title: 'Exchange setup'
                fields: ['publisher', 'name', 'bidfloor', 'country', 'atribution_type', 'blocked_categories', 'blocked_advertisers', 'whitelist_seats']
                sort: 'name'
            form:
                fields: ['name', 'publisher', 'bidfloor', 'country', 'atribution_type', 'blocked_categories', 'blocked_advertisers', 'whitelist_seats']

        Deals:
            class: App\Entity\Deals
            label: 'Deals'
            list:
                title: 'Deals with advertisers'
                fields: ['publisher', 'name', 'whitelist_seats', 'bidfloor', 'atribution_type', 'private_auction']

    design:
        brand_color: 'red'
        assets:
            favicon: 'https://www.vidoomy.com/favicon.ico'
        menu:
            - { label: 'Stats', icon: 'bar-chart', url: '/admin/stats' }
            - { entity: 'Deals', icon: 'handshake-o' }
            - { entity: 'Setup', icon: 'gear' }