<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZ1yb3S\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZ1yb3S/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXZ1yb3S.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXZ1yb3S\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXZ1yb3S\App_KernelProdContainer([
    'container.build_hash' => 'XZ1yb3S',
    'container.build_id' => '897f7de3',
    'container.build_time' => 1591723562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZ1yb3S');
