<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'stats' => [[], ['_controller' => 'App\\Controller\\StatsController::index'], [], [['text', '/admin/stats']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\StatsController::home'], [], [['text', '/']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController::indexAction'], [], [['text', '/admin/']], [], []],
];
